services:
  db:
    image: postgres:16
    container_name: matcher_db
    env_file:
      - .base.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  liquibase:
    image: liquibase/liquibase:latest-alpine
    container_name: matcher-liquibase
    depends_on:
      db:
        condition: service_healthy
    environment:
      INIT_COMMAND_URL: "jdbc:postgresql://localhost:5433/matcher?autoReconnect=true&useSSL=false"
      INIT_COMMAND_CHANGELOG_FILE: "changelog-init.xml"
      LIQUIBASE_LOG_LEVEL: "info"
      LIQUIBASE_CLASSPATH: "/liquibase/changelog"
      LIQUIBASE_COMMAND_URL: "jdbc:postgresql://localhost:5433/matcher?autoReconnect=true&useSSL=false"
      LIQUIBASE_COMMAND_USERNAME: "matcher"
      LIQUIBASE_COMMAND_PASSWORD: "matcher"
      LIQUIBASE_COMMAND_CHANGELOG_FILE: "changelog.xml"
    volumes:
      - ./liquibase:/liquibase/changelog
    command: >
      sh -c "
      liquibase --url=$$INIT_COMMAND_URL --changeLogFile=$$INIT_COMMAND_CHANGELOG_FILE update
      &&
      liquibase update
      "